# Generated by Django 5.0.3 on 2024-04-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                # ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/', blank=True, null=True)),
                ('start_preorder_date', models.DateTimeField()),
                ('end_preorder_date', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(choices=[('WAITING_PAYMENT', 'Waiting for payment'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('recipient_phone_number', models.CharField(max_length=15)),
                ('courier_company', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=50)),
                ('shipping_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.order')),
            ],
        ),
    ]
